<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.8</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>

  <groupId>io.github.rromanowicz</groupId>
  <artifactId>apicaller</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <packaging>pom</packaging>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>Collection of REST client wrappers with built-in logging</description>
  <url>https://github.com/rromanowicz/ApiCaller</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>Robert Romanowicz</name>
      <email>rromanowicz@hotmail.com</email>
      <organization>rromanowicz</organization>
      <organizationUrl>https://github.com/rromanowicz</organizationUrl>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/rromanowicz/ApiCaller.git</connection>
    <developerConnection>scm:git:ssh://github.com:rromanowicz/ApiCaller.git</developerConnection>
    <url>http://github.com/rromanowicz/ApiCaller/tree/master</url>
  </scm>

  <modules>
    <module>common</module>
    <module>core</module>
    <module>incoming</module>
    <module>restclient</module>
    <module>unirest</module>
    <module>webclient</module>
    <module>test</module>
  </modules>

  <properties>
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <unirest.bom.version>4.5.1</unirest.bom.version>
    <apache.commons.version>3.18.0</apache.commons.version>
    <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>restclient</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>unirest</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>webclient</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>test</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.github.rromanowicz.apicaller</groupId>
        <artifactId>incoming</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${apache.commons.version}</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.20.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>2.2.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>2.9.1</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
        <version>1.5</version>
        <executions>
          <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
              <goal>sign</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
        <version>0.9.0</version>
        <extensions>true</extensions>
        <configuration>
          <checksums>all</checksums>
          <publishingServerId>central</publishingServerId>
          <autoPublish>true</autoPublish>
          <skipPublishing>true</skipPublishing>
          <excludeArtifacts>
            <artifactId>test</artifactId>
          </excludeArtifacts>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
