<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.8</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.rromanowicz</groupId>
  <artifactId>apicaller</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>apicaller</name>
  <description>Universal REST client wrapper</description>

  <developers>
    <developer>
      <id>rromanowicz</id>
      <name>Robert Romanowicz</name>
      <email>rromanowicz@pm.me</email>
      <roles>
        <role>developer</role>
      </roles>
    </developer>
  </developers>

  <modules>
    <module>common</module>
    <module>core</module>
    <module>incoming</module>
    <module>restclient</module>
    <module>unirest</module>
    <module>webclient</module>
    <module>test</module>
  </modules>

  <properties>
    <java.version>21</java.version>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <unirest.bom.version>4.5.1</unirest.bom.version>
    <apache.commons.version>3.18.0</apache.commons.version>
    <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>restclient</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>unirest</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>webclient</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>common</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>test</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>com.rromanowicz.apicaller</groupId>
        <artifactId>incoming</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>${apache.commons.version}</version>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.20.0</version>
    </dependency>
  </dependencies>

</project>
