logging.level.com.rromanowicz.apicaller=INFO
app.logging.enabled.incoming=true
app.logging.enabled.outgoing=true
app.logging.enabled.payload,incoming.request=true
app.logging.enabled.payload,incoming.response=true
app.logging.enabled.payload,outgoing.request=true
app.logging.enabled.payload,outgoing.response=true
